language: node_js
deploy:
  provider: npm
  email: scjosh2@gmail.com
  api_key:
    secure: oRxIBvd9As3QGfgwjFZVbAaYAelVXy4LWDMRwK0oXOeDkeOXiAdk26AY47l6VLc0XoLvipkpNkJ3Rc68pDBb+3Pny1QDVW8U6gPh7IuM729NLcvisciR/vF/rWmFZnTKNXu6ZDUqNJrZxzOd6RHa6Z4y9WdiFjDw+rdYOQYJh70=
  on:
    repo: joshuaferrara/node-csgo
node_js:
- '0.12'
- '0.11'
- '0.10'
sudo: false
